spring:
    application:
        name: lab5
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    datasource:
        url: jdbc:postgresql://localhost:5432/food_service
        username: trroooyyyy
        password: "06062023"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

rapidApi:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"